name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests-debug:
    name: Debug mode unit tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: sudo apt-get update -qq
    - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - run: sudo apt-get update -qq
    - run: sudo apt-get install -qq cmake build-essential python3-pip python3-virtualenv nodejs tar gzip libpthread-stubs0-dev libc6-dbg gdb
    - run: clang++ --version
    - run: g++ --version
    - name: run-tests
      run: make test-unit

  regression-tests-native:
    name: Regression tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - run: sudo apt-get update -qq
    - run: sudo apt-get install -qq cmake build-essential python3-pip python3-virtualenv nodejs tar gzip libpthread-stubs0-dev libc6-dbg gdb
      #- run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
    - run: clang++ --version
    - run: g++ --version
    - name: run-tests
      run: make test-regression
